### ISSUE TITLE
For Phi-3-Vision, when num_crops=1, removing the repeated HD image

### ISSUE THREAD

**Issue by Gaozhongpai** [microsoft/Phi-3CookBook#112]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [x] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

During the fine-tuning or inference, is it possible to remove the repeated HD image when num_crops=1 for low-resolution input images?

**Comment by leestott** [comment]
with num_crops = 1, the processor created an unnecessary crop that is identical to the global image. Basically doubling the pixel_values size?

Yes, there will be one global image and one HD image of 1x1 (which is essentially the same as the global image). I'd assume those who wish to tune num_crops understand this consequence.
The blank images are paddings, see [here](https://huggingface.co/microsoft/Phi-3-vision-128k-instruct/blob/866d1691437a49af79d5f3ad4a34c1750e08d163/image_processing_phi3_v.py#L261). 

Since the example you used is a near square image, the resulting HD image will always be squared (1x1, 2x2, ... 4x4). The num_crops hyper-parameter specifies the upper bound of total HD patches, i.e., W * H <= num_crops for the W x H HD image (W and H being integers). 

If you try images with more extreme aspect ratio, say 3:1, you should see the effects.

**Comment by Gaozhongpai** [comment]
> with num_crops = 1, the processor created an unnecessary crop that is identical to the global image. Basically doubling the pixel_values size?
> 
> Yes, there will be one global image and one HD image of 1x1 (which is essentially the same as the global image). I'd assume those who wish to tune num_crops understand this consequence. The blank images are paddings, see [here](https://huggingface.co/microsoft/Phi-3-vision-128k-instruct/blob/866d1691437a49af79d5f3ad4a34c1750e08d163/image_processing_phi3_v.py#L261).
> 
> Since the example you used is a near square image, the resulting HD image will always be squared (1x1, 2x2, ... 4x4). The num_crops hyper-parameter specifies the upper bound of total HD patches, i.e., W * H <= num_crops for the W x H HD image (W and H being integers).
> 
> If you try images with more extreme aspect ratio, say 3:1, you should see the effects.

Yes, I understand that. What I mean is that we can remove the repeated HD image tokens to save half of the input token length.

**Comment by leestott** [comment]
@ChenRocks suggestion change to vision example

**Comment by ChenRocks** [comment]
Thanks for reporting. As mentioned in #105, this is not the intended usage so we don't plan to officially support it as of now. IMHO, without HD image, it will become a different model from Phi-3-V. However, feel free to clone the huggingface model to experiment with your own model variants 😊
