### ISSUE TITLE
Warning issue with flash attention

### ISSUE THREAD

**Issue by HarikrishnanK9** [microsoft/Phi-3CookBook#115]
WARNING:transformers_modules.microsoft.Phi-3-mini-4k-instruct.c1358f8a35e6d2af81890deffbbfa575b978c62f.modeling_phi3:You are not running the flash-attention implementation, expect numerical differences.
You are not running the flash-attention implementation, expect numerical differences.
<IPython.core.display.Markdown object>
None

**Comment by skytin1004** [comment]
Hi @HarikrishnanK9, Thank you for bringing up this issue. The warning message indicates that you are not running the flash-attention implementation, which may result in numerical differences. However, I want to assure you that this does not impact the actual fine-tuning process. Using flash-attention can provide certain performance benefits, but it is not essential for fine-tuning.

Some tutorials might apply different methods, such as using eager attention instead of flash-attention, which can trigger the warning mentioned. Again, this warning does not affect the fine-tuning process itself.

**Comment by skytin1004** [comment]
@HarikrishnanK9 If you wish to use "flash_attention_2," you can download the necessary package by running the following command:

```bash
pip install flash_attn
```
Then, update the model configuration as shown below:

```python
model_kwargs = {
    "use_cache": False,
    "trust_remote_code": True,
    "torch_dtype": torch.bfloat16,
    "device_map": None,
    "attn_implementation": "flash_attention_2"
}
```
Please note that "flash_attention_2" is only available on certain GPUs.

For more information, you may find these [Guide on fine-tuning a Phi-3-mini model for Python code generation utilizing QLoRA via Hugging Face Hub](https://github.com/microsoft/Phi-3CookBook/blob/main/code/04.Finetuning/Phi-3-finetune-qlora-python.ipynb),  [Instruction for fine-tuning a Phi-3-mini model on Python code generation using LoRA via Hugging Face Hub](https://github.com/microsoft/Phi-3CookBook/blob/main/code/04.Finetuning/Phi-3-finetune-lora-python.ipynb) documents helpful, as it describes the fine-tuning process using flash_attention

**Comment by HarikrishnanK9** [comment]
Thank You @skytin1004 The issue is resolved     "attn_implementation": "flash_attention_2" in model kwargs worked for me.

**Comment by vizsatiz** [comment]
I just got the error

`The following `model_kwargs` are not used by the model: ['attn_implementation'] (note: typos in the generate arguments will also show up in this list)`

@skytin1004 Any idea why ? I am running the interference API on A100 series Nvidia

**Comment by skytin1004** [comment]
> I just got the error
> 
> `The following `model_kwargs` are not used by the model: ['attn_implementation'] (note: typos in the generate arguments will also show up in this list)`
> 
> @skytin1004 Any idea why ? I am running the interference API on A100 series Nvidia

Hi @vizsatiz,

I’m not sure of the exact cause of your issue, as A100 GPUs should support flash_attention without problems. It’s possible that the issue lies with the installation of the flash_attn package itself. I recommend checking the version of flash_attn you have installed and verifying that it is compatible with both your current transformer version and CUDA setup
