### ISSUE TITLE
The model requires too much GPU memory to process input prompt

### ISSUE THREAD

**Issue by TianyuFan0504** [microsoft/Phi-3CookBook#218]
When I use Phi-3.5-mini-instruct model, I found that the required memory for processing inputs is much more larger than other models/what is theoretically needed.

Here is the code and the CUDA error:
```
import os
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer, pipeline

os.environ['CUDA_VISIBLE_DEVICES'] = '1'
# MODEL = "mistralai/Ministral-8B-Instruct-2410" #will not cause OOM error
MODEL = "microsoft/Phi-3.5-mini-instruct" #will cause OOM error

model = AutoModelForCausalLM.from_pretrained(
    MODEL, 
    device_map="auto", 
    torch_dtype="auto", 
    trust_remote_code=True, 
)
tokenizer = AutoTokenizer.from_pretrained(MODEL)

messages = [
    {"role": "system", "content": SYSPROMPT},#len(SYSPROMPT) = 50000
    {"role": "user", "content": "1+1 = ?"},
]

pipe = pipeline(
    "text-generation",
    model=model,
    tokenizer=tokenizer,
)

generation_args = {
    "max_new_tokens": 500,
    "return_full_text": False,
    "temperature": 0.0,
    "do_sample": False,
}

output = pipe(messages, **generation_args)
print(output[0]['generated_text'])
```

and the error is:
```
OutOfMemoryError: CUDA out of memory. Tried to allocate 18.40 GiB. 
```

I don't think processing 50k prompts requires an additional 18GB of memory. In fact, even some larger models (Like 8B) won't produce OOM error.

Why is that? Can anyone help?

**Comment by leestott** [comment]
Hi @TianyuFan0504 The Phi-3.5-mini-instruct model, despite being lightweight, can still be quite demanding due to its architecture and the large context length it supports (128K tokens). 

Here are a few potential reasons and suggestions but it simply looks like your local machine doesn't have enough available GPU memory:

Potential Reasons:
Large Context Length: Supporting 128K tokens means the model needs to keep a lot of information in memory, which can be memory-intensive.

Model Size: Even though it's considered lightweight, 3.5 billion parameters are still significant and require substantial memory.

Parallel Processing: Generating embeddings in parallel with Phi-3 and CLIP might be adding to the memory load.

Suggestions you should look at:

1.Reduce Batch Size: Lowering the batch size can help manage memory usage.
2.Gradient Checkpointing: This technique can reduce memory consumption by trading compute for memory.
3. Use Efficient Hardware: Ensure you're using the most efficient hardware available, like NVIDIA GPUs with high memory capacity for example I always use a A100 in Azure for Finetuning for this reason.
