### ISSUE TITLE
Error about tokenizer?

### ISSUE THREAD

**Issue by xushilin1** [microsoft/Phi-3CookBook#82]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> tokenizer.decode(tokenizer('<|user|>\nhello').input_ids)

The output of this line of code is `<|user|> hello`. Why not `<|user|>\nhello`

### Expected/desired behavior
>

### Versions
> transformers==4.41.2

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by leestott** [comment]
hi @xushilin1  can you please confirm which sample or tutorial this error is in?

**Comment by leestott** [comment]
@xushilin1 In the given example, where you're using a tokenizer from Hugging Face's Transformers library version 4.41.2

Here is explanation why the output of `decode(tokenizer('<|user|> \nhello').input_ids)` would be "<|user|>  hello" and not "<|user|>  \nhello":

1. Tokenization: When passing the string '<|user|> \nhello' to the tokenizer (assuming you use SentencePiece or a similar tokenizer), it splits this text into tokens, treating '\n' as its own distinct token along with '<|user|> '. The output will be ['<|user|> ', '\n', 'hello'], where each item in the list corresponds to an input_id.

2. Decoding: When you call `tokenizer.decode(input_ids)`, it converts these integers back into their corresponding tokens using a reverse-lookup table from the tokenizer's vocabulary. However, when converting lists of tokens back to strings in Python, the function ignores any separators (such as '\n') and only includes the actual tokens.

Therefore, `tokenizer.decode(['<|user|> ', '\n', 'hello'])` results in "<|user|>  hello". The newline character ('\n') is not included in the output string since it's treated as a separate token during the decoding process.

**Comment by leestott** [comment]
@xushilin1 In the given example, where you're using a tokenizer from Hugging Face's Transformers library version 4.41.2

Here is explaination why the output of `decode(tokenizer('<|user|> \nhello').input_ids)` would be "<|user|>  hello" and not "<|user|>  \nhello":

1. Tokenization: When passing the string '<|user|> \nhello' to the tokenizer (assuming you use SentencePiece or a similar tokenizer), it splits this text into tokens, treating '\n' as its own distinct token along with '<|user|> '. The output will be ['<|user|> ', '\n', 'hello'], where each item in the list corresponds to an input_id.

2. Decoding: When you call `tokenizer.decode(input_ids)`, it converts these integers back into their corresponding tokens using a reverse-lookup table from the tokenizer's vocabulary. However, when converting lists of tokens back to strings in Python, the function ignores any separators (such as '\n') and only includes the actual tokens.

Therefore, `tokenizer.decode(['<|user|> ', '\n', 'hello'])` results in "<|user|>  hello". The newline character ('\n') is not included in the output string since it's treated as a separate token during the decoding process.
